module.exports = [
    'position',
    'top',
    'right',
    'bottom',
    'left',
    'z-index',

    'display',
    'visibility',
    'content',

    'grid',
    'grid-area',
    'grid-auto-columns',
    'grid-auto-flow',
    'grid-auto-rows',
    'grid-column',
    'grid-column-end',
    'grid-column-gap',
    'grid-column-start',
    'grid-gap',
    'grid-row',
    'grid-row-end',
    'grid-row-gap',
    'grid-row-start',
    'grid-template',
    'grid-template-areas',
    'grid-template-columns',
    'grid-template-rows',
    'gap',

    'flex',
    'flex-grow',
    'flex-shrink',
    'flex-basis',
    'flex-flow',
    'flex-direction',
    'flex-wrap',
    'justify-content',
    'align-content',
    'align-items',
    'align-self',
    'order',

    'float',
    'clear',
];
