module.exports = [
    'font',
    'font-family',
    'font-size',
    'font-weight',
    'font-style',
    'font-variant',
    'font-size-adjust',
    'font-stretch',
    'font-effect',
    'font-emphasize',
    'font-emphasize-position',
    'font-emphasize-style',
    'font-smooth',

    'direction',

    'line-height',
    'letter-spacing',
    'word-spacing',
    'tab-size',

    'text-align',
    'text-align-last',
    'text-transform',
    'text-decoration',
    'text-emphasis',
    'text-emphasis-color',
    'text-emphasis-style',
    'text-emphasis-position',
    'text-indent',
    'text-justify',
    'text-outline',
    'text-orientation',
    'text-shadow',

    'text-wrap',
    'word-wrap',
    'word-break',
    'white-space',
    'page-break-after',
    'page-break-before',
    'page-break-inside',
    'text-overflow',
    'text-overflow-ellipsis',
    'text-overflow-mode',
    'overflow-wrap',
    'hyphens',

    'vertical-align',

    'columns',
    'column-count',
    'column-fill',
    'column-gap',
    'column-rule',
    'column-rule-color',
    'column-rule-style',
    'column-rule-width',
    'column-span',
    'column-width',

    'unicode-bidi',
    'src',
  ];
